import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

/// The app mark generated by tool/branding/make_icon.py, and the platform
/// files that point at it.
void main() {
  group('bundled mark', () {
    for (final (path, size) in [
      ('assets/branding/icon.png', 1024),
      ('assets/branding/mark_128.png', 128),
    ]) {
      testWidgets('$path loads with Image.asset', (tester) async {
        await tester.pumpWidget(Center(child: Image.asset(path, width: 40, height: 40)));
        final provider = tester.widget<Image>(find.byType(Image)).image;
        final info = (await tester.runAsync(() => _resolve(provider)))!;
        addTearDown(info.dispose);
        expect((info.image.width, info.image.height), (size, size));

        await tester.pump();
        expect(tester.takeException(), isNull);
        expect(tester.widget<RawImage>(find.byType(RawImage)).image, isNotNull);
      });
    }
  });

  group('platform metadata', () {
    test('the web head links icons that exist', () {
      final html = File('web/index.html').readAsStringSync();
      for (final href in ['favicon.ico', 'favicon.png', 'apple-touch-icon.png']) {
        expect(html, contains('href="$href"'));
        expect(File('web/$href').existsSync(), isTrue, reason: href);
      }
      final manifest = jsonDecode(File('web/manifest.json').readAsStringSync()) as Map<String, dynamic>;
      for (final icon in manifest['icons'] as List) {
        final src = (icon as Map<String, dynamic>)['src'] as String;
        expect(File('web/$src').existsSync(), isTrue, reason: src);
      }
    });

    test('iOS shows a localized name under the icon', () {
      expect(File('ios/Runner/en.lproj/InfoPlist.strings').readAsStringSync(),
          contains('"CFBundleDisplayName" = "Shnayim Mikra";'));
      expect(File('ios/Runner/he.lproj/InfoPlist.strings').readAsStringSync(),
          contains('"CFBundleDisplayName" = "שניים מקרא";'));
      final project = File('ios/Runner.xcodeproj/project.pbxproj').readAsStringSync();
      expect(project, contains('path = he.lproj/InfoPlist.strings;'));
      expect(project, contains('/* InfoPlist.strings in Resources */,'));
      expect(RegExp(r'knownRegions = \([^)]*\bhe,').hasMatch(project), isTrue);
    });
  });
}

/// Decodes [provider] once, outside the fake-async zone.
Future<ImageInfo> _resolve(ImageProvider provider) {
  final completer = Completer<ImageInfo>();
  final stream = provider.resolve(ImageConfiguration.empty);
  late final ImageStreamListener listener;
  listener = ImageStreamListener(
    (info, _) {
      stream.removeListener(listener);
      completer.complete(info);
    },
    onError: (error, stack) {
      stream.removeListener(listener);
      completer.completeError(error, stack);
    },
  );
  stream.addListener(listener);
  return completer.future;
}
