import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shnayim_mikra/ui/theme/palette.dart';

/// The app mark generated by tool/branding/make_icon.py, and the platform
/// files that point at it.
void main() {
  group('bundled mark', () {
    for (final (path, size) in [
      ('assets/branding/icon.png', 1024),
      ('assets/branding/mark_128.png', 128),
    ]) {
      testWidgets('$path loads with Image.asset', (tester) async {
        await tester.pumpWidget(Center(child: Image.asset(path, width: 40, height: 40)));
        final provider = tester.widget<Image>(find.byType(Image)).image;
        final info = (await tester.runAsync(() => _resolve(provider)))!;
        addTearDown(info.dispose);
        expect((info.image.width, info.image.height), (size, size));

        await tester.pump();
        expect(tester.takeException(), isNull);
        expect(tester.widget<RawImage>(find.byType(RawImage)).image, isNotNull);
      });
    }
  });

  group('platform metadata', () {
    test('the web head links icons that exist', () {
      final html = File('web/index.html').readAsStringSync();
      for (final href in ['favicon.ico', 'favicon.png', 'apple-touch-icon.png']) {
        expect(html, contains('href="$href"'));
        expect(File('web/$href').existsSync(), isTrue, reason: href);
      }
      final manifest = jsonDecode(File('web/manifest.json').readAsStringSync()) as Map<String, dynamic>;
      for (final icon in manifest['icons'] as List) {
        final src = (icon as Map<String, dynamic>)['src'] as String;
        expect(File('web/$src').existsSync(), isTrue, reason: src);
      }
    });

    // make_icon.py --post must run after flutter_launcher_icons, which
    // otherwise leaves a 16 px downscale of the whole wordmark as the favicon
    // and the unpadded master as the maskable icons.
    testWidgets('favicon.png is the 32 px tile of three rules', (tester) async {
      final image = await _decode(tester, 'web/favicon.png');
      expect((image.width, image.height), (32, 32));
    });

    for (final size in [192, 512]) {
      testWidgets('Icon-maskable-$size.png pads the mark well inside the safe circle', (tester) async {
        final maskable = await _decode(tester, 'web/icons/Icon-maskable-$size.png');
        final plain = await _decode(tester, 'web/icons/Icon-$size.png');
        expect((maskable.width, maskable.height), (size, size));
        final reach = await _inkReach(tester, maskable);
        // Masks may cut anything beyond 40% of the width from the centre;
        // the mark is drawn at 90% of the master's size, well inside that.
        expect(reach, lessThan(0.4 * size));
        expect(reach, lessThan(0.92 * await _inkReach(tester, plain)));
      });
    }

    group('launch screens', () {
      // flutter_native_splash reads it at 4×: 288 dp or pt.
      testWidgets('the logo is the tile, inside the circle Android 12 shows', (tester) async {
        final logo = await _decode(tester, 'assets/branding/splash_logo.png');
        expect((logo.width, logo.height), (1152, 1152));
        final reach = await _reach(tester, logo, (r, g, b, a) => a > 0);
        // Android 12 and later show only the central 192 dp (768 px).
        expect(reach, lessThan(384));
        // The tile is 576 px wide: corners at 22% reach 355 px.
        expect(reach, greaterThan(340));
      });

      // The launch screen is the colour of the first frame, so nothing
      // flashes between them.
      test('Android starts on the app surface, light and dark', () {
        for (final (dir, surface) in [('values', Palettes.light.surface), ('values-night', Palettes.dark.surface)]) {
          final colors = File('android/app/src/main/res/$dir/colors.xml').readAsStringSync();
          expect(colors, contains('<color name="app_bg">${_hex(surface)}</color>'), reason: dir);
        }
        for (final (dir, surface) in [('values-v31', Palettes.light.surface), ('values-night-v31', Palettes.dark.surface)]) {
          final styles = File('android/app/src/main/res/$dir/styles.xml').readAsStringSync();
          expect(styles, contains('<item name="android:windowSplashScreenBackground">${_hex(surface)}</item>'),
              reason: dir);
          expect(styles, contains('<item name="android:windowSplashScreenAnimatedIcon">@drawable/android12splash</item>'),
              reason: dir);
          expect(styles, isNot(contains('windowSplashScreenIconBackgroundColor')), reason: dir);
        }
        for (final dir in ['drawable', 'drawable-v21', 'drawable-night', 'drawable-night-v21']) {
          final background = File('android/app/src/main/res/$dir/launch_background.xml').readAsStringSync();
          expect(background, contains('android:src="@drawable/background"'), reason: dir);
          expect(background, contains('android:src="@drawable/splash"'), reason: dir);
        }
      });

      for (final (path, surface) in [
        ('android/app/src/main/res/drawable-v21/background.png', Palettes.light.surface),
        ('android/app/src/main/res/drawable-night-v21/background.png', Palettes.dark.surface),
        ('ios/Runner/Assets.xcassets/LaunchBackground.imageset/background.png', Palettes.light.surface),
        ('ios/Runner/Assets.xcassets/LaunchBackground.imageset/darkbackground.png', Palettes.dark.surface),
      ]) {
        testWidgets('$path is the surface', (tester) async {
          final image = await _decode(tester, path);
          final pixel = (await tester.runAsync(() => image.toByteData()))!;
          expect(Color.fromARGB(pixel.getUint8(3), pixel.getUint8(0), pixel.getUint8(1), pixel.getUint8(2)), surface);
        });
      }

      test('iOS draws the logo over the background', () {
        final storyboard = File('ios/Runner/Base.lproj/LaunchScreen.storyboard').readAsStringSync();
        expect(storyboard, contains('image="LaunchBackground"'));
        expect(storyboard, contains('image="LaunchImage"'));
        final launchImage = jsonDecode(
          File('ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json').readAsStringSync(),
        ) as Map<String, dynamic>;
        expect([for (final i in launchImage['images'] as List) (i as Map<String, dynamic>)['filename']],
            ['LaunchImage.png', 'LaunchImage@2x.png', 'LaunchImage@3x.png']);
      });
    });

    test('iOS shows a localized name under the icon', () {
      expect(File('ios/Runner/en.lproj/InfoPlist.strings').readAsStringSync(),
          contains('"CFBundleDisplayName" = "Shnayim Mikra";'));
      expect(File('ios/Runner/he.lproj/InfoPlist.strings').readAsStringSync(),
          contains('"CFBundleDisplayName" = "שניים מקרא";'));
      final project = File('ios/Runner.xcodeproj/project.pbxproj').readAsStringSync();
      expect(project, contains('path = he.lproj/InfoPlist.strings;'));
      expect(project, contains('/* InfoPlist.strings in Resources */,'));
      expect(RegExp(r'knownRegions = \([^)]*\bhe,').hasMatch(project), isTrue);
    });
  });
}

/// Decodes the PNG at [path], outside the fake-async zone.
Future<ui.Image> _decode(WidgetTester tester, String path) async {
  final image = (await tester.runAsync(() async {
    final codec = await ui.instantiateImageCodec(File(path).readAsBytesSync());
    return (await codec.getNextFrame()).image;
  }))!;
  addTearDown(image.dispose);
  return image;
}

/// How far from the centre the icon's cream and gold ink reaches, in pixels.
/// The blue gradient behind it is dark in every channel.
Future<double> _inkReach(WidgetTester tester, ui.Image image) => _reach(tester, image, (r, g, b, a) => r > 0x80);

/// How far from the centre of [image] the pixels that are [ink] reach.
Future<double> _reach(WidgetTester tester, ui.Image image, bool Function(int r, int g, int b, int a) ink) async {
  final pixels = (await tester.runAsync(() => image.toByteData()))!;
  final centre = image.width / 2;
  var reach = 0.0;
  for (var y = 0; y < image.height; y++) {
    for (var x = 0; x < image.width; x++) {
      final i = (y * image.width + x) * 4;
      if (ink(pixels.getUint8(i), pixels.getUint8(i + 1), pixels.getUint8(i + 2), pixels.getUint8(i + 3))) {
        reach = math.max(reach, math.sqrt(math.pow(x + 0.5 - centre, 2) + math.pow(y + 0.5 - centre, 2)));
      }
    }
  }
  return reach;
}

/// [color] as Android writes it, #RRGGBB.
String _hex(Color color) => '#${(color.toARGB32() & 0xFFFFFF).toRadixString(16).padLeft(6, '0').toUpperCase()}';

/// Decodes [provider] once, outside the fake-async zone.
Future<ImageInfo> _resolve(ImageProvider provider) {
  final completer = Completer<ImageInfo>();
  final stream = provider.resolve(ImageConfiguration.empty);
  late final ImageStreamListener listener;
  listener = ImageStreamListener(
    (info, _) {
      stream.removeListener(listener);
      completer.complete(info);
    },
    onError: (error, stack) {
      stream.removeListener(listener);
      completer.completeError(error, stack);
    },
  );
  stream.addListener(listener);
  return completer.future;
}
