import 'package:flutter/material.dart';

import 'sefer_colors.dart';
import 'status_colors.dart';

export 'sefer_colors.dart';
export 'status_colors.dart';

/// The Klaf & Techelet palette (docs/DESIGN_SYSTEM.md §3): every colour the
/// app paints, for each of the five themes. Every ColorScheme role is set
/// explicitly, so no stock widget falls back to a seeded colour, and
/// test/ui/palette_contrast_test.dart locks in the contrast of every pair
/// that carries text or meaning.
///
/// How the roles are used:
/// - primary (techelet) only for interaction, Mikra progress, the focus ring
///   and the Hebrew display title of a parsha;
/// - secondary (gold ink) is the rubric colour: eyebrows, verse numbers,
///   chapter heads, Targum, overdue and rest days. Never buttons;
/// - tertiary (hyssop) only for grace;
/// - missed is neutral plus a dash glyph, never red;
/// - error only for validation and destructive confirmations.
///
/// The fixed roles repeat the container roles, so a widget that reaches for
/// primaryFixed still gets the palette's colour.
abstract final class Palettes {
  /// Light, "Klaf": warm parchment and warm ink.
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF1D3F75),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFDDE5F2),
    onPrimaryContainer: Color(0xFF0E2547),
    primaryFixed: Color(0xFFDDE5F2),
    primaryFixedDim: Color(0xFFDDE5F2),
    onPrimaryFixed: Color(0xFF0E2547),
    onPrimaryFixedVariant: Color(0xFF0E2547),
    secondary: Color(0xFF7A5712),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFF2E7CD),
    onSecondaryContainer: Color(0xFF3B2A06),
    secondaryFixed: Color(0xFFF2E7CD),
    secondaryFixedDim: Color(0xFFF2E7CD),
    onSecondaryFixed: Color(0xFF3B2A06),
    onSecondaryFixedVariant: Color(0xFF3B2A06),
    tertiary: Color(0xFF2E6A56),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFD5EADF),
    onTertiaryContainer: Color(0xFF0B3B2C),
    tertiaryFixed: Color(0xFFD5EADF),
    tertiaryFixedDim: Color(0xFFD5EADF),
    onTertiaryFixed: Color(0xFF0B3B2C),
    onTertiaryFixedVariant: Color(0xFF0B3B2C),
    error: Color(0xFF9A2B2B),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFF6DEDA),
    onErrorContainer: Color(0xFF5C1414),
    surface: Color(0xFFFAF7F0),
    onSurface: Color(0xFF1E1A16),
    surfaceDim: Color(0xFFE6DFD1),
    surfaceBright: Color(0xFFFFFDF8),
    surfaceContainerLowest: Color(0xFFFFFDF8),
    surfaceContainerLow: Color(0xFFF4EFE4),
    surfaceContainer: Color(0xFFEEE8DB),
    surfaceContainerHigh: Color(0xFFE8E1D2),
    surfaceContainerHighest: Color(0xFFE0D8C7),
    onSurfaceVariant: Color(0xFF575046),
    outline: Color(0xFF857B6D),
    outlineVariant: Color(0xFFD8CFBF),
    shadow: Color(0xFF1E1A16),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF2E2924),
    onInverseSurface: Color(0xFFF4EFE4),
    inversePrimary: Color(0xFFAFC6EE),
    surfaceTint: Colors.transparent,
  );

  /// Dark, "Lamplight": warm ink-dark surfaces with parchment-coloured text.
  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFAFC6EE),
    onPrimary: Color(0xFF0E2547),
    primaryContainer: Color(0xFF27416B),
    onPrimaryContainer: Color(0xFFDDE7F8),
    primaryFixed: Color(0xFF27416B),
    primaryFixedDim: Color(0xFF27416B),
    onPrimaryFixed: Color(0xFFDDE7F8),
    onPrimaryFixedVariant: Color(0xFFDDE7F8),
    secondary: Color(0xFFDDB96B),
    onSecondary: Color(0xFF2E2205),
    secondaryContainer: Color(0xFF4A3A16),
    onSecondaryContainer: Color(0xFFF4E5BC),
    secondaryFixed: Color(0xFF4A3A16),
    secondaryFixedDim: Color(0xFF4A3A16),
    onSecondaryFixed: Color(0xFFF4E5BC),
    onSecondaryFixedVariant: Color(0xFFF4E5BC),
    tertiary: Color(0xFF8FD0B6),
    onTertiary: Color(0xFF003829),
    tertiaryContainer: Color(0xFF1F4A3C),
    onTertiaryContainer: Color(0xFFC9EEDD),
    tertiaryFixed: Color(0xFF1F4A3C),
    tertiaryFixedDim: Color(0xFF1F4A3C),
    onTertiaryFixed: Color(0xFFC9EEDD),
    onTertiaryFixedVariant: Color(0xFFC9EEDD),
    error: Color(0xFFF2B8B5),
    onError: Color(0xFF601410),
    errorContainer: Color(0xFF5C1A17),
    onErrorContainer: Color(0xFFFFDAD5),
    surface: Color(0xFF14120F),
    onSurface: Color(0xFFEDE6D6),
    surfaceDim: Color(0xFF14120F),
    surfaceBright: Color(0xFF3A352E),
    surfaceContainerLowest: Color(0xFF0F0D0B),
    surfaceContainerLow: Color(0xFF1C1915),
    surfaceContainer: Color(0xFF221F1A),
    surfaceContainerHigh: Color(0xFF2B2721),
    surfaceContainerHighest: Color(0xFF36312A),
    onSurfaceVariant: Color(0xFFC4BAA8),
    outline: Color(0xFF928878),
    outlineVariant: Color(0xFF4A443A),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFEDE6D6),
    onInverseSurface: Color(0xFF1E1A16),
    inversePrimary: Color(0xFF1D3F75),
    surfaceTint: Colors.transparent,
  );

  /// Sepia, "Vellum": a deeper parchment for long reading.
  static const sepia = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF25406C),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD7DBE1),
    onPrimaryContainer: Color(0xFF142A4D),
    primaryFixed: Color(0xFFD7DBE1),
    primaryFixedDim: Color(0xFFD7DBE1),
    onPrimaryFixed: Color(0xFF142A4D),
    onPrimaryFixedVariant: Color(0xFF142A4D),
    secondary: Color(0xFF6C4B0E),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFEADBB4),
    onSecondaryContainer: Color(0xFF3A2905),
    secondaryFixed: Color(0xFFEADBB4),
    secondaryFixedDim: Color(0xFFEADBB4),
    onSecondaryFixed: Color(0xFF3A2905),
    onSecondaryFixedVariant: Color(0xFF3A2905),
    tertiary: Color(0xFF2B6350),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFD3E3D3),
    onTertiaryContainer: Color(0xFF0E3528),
    tertiaryFixed: Color(0xFFD3E3D3),
    tertiaryFixedDim: Color(0xFFD3E3D3),
    onTertiaryFixed: Color(0xFF0E3528),
    onTertiaryFixedVariant: Color(0xFF0E3528),
    error: Color(0xFF8E2A22),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFF1D5C9),
    onErrorContainer: Color(0xFF4F120C),
    surface: Color(0xFFF3E9D2),
    onSurface: Color(0xFF2B2115),
    surfaceDim: Color(0xFFE1D4B6),
    surfaceBright: Color(0xFFFAF3E3),
    surfaceContainerLowest: Color(0xFFFAF3E3),
    surfaceContainerLow: Color(0xFFEDE2C8),
    surfaceContainer: Color(0xFFE7DBBF),
    surfaceContainerHigh: Color(0xFFE1D4B6),
    surfaceContainerHighest: Color(0xFFD8CAA9),
    onSurfaceVariant: Color(0xFF54452F),
    outline: Color(0xFF83704F),
    outlineVariant: Color(0xFFCBB994),
    shadow: Color(0xFF2B2115),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF3A2F20),
    onInverseSurface: Color(0xFFF3E9D2),
    inversePrimary: Color(0xFFB4C6E6),
    surfaceTint: Colors.transparent,
  );

  /// High contrast light: black on white, every text pair at 7:1 or more.
  static const hcLight = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF0A2A5E),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFDCE6FA),
    onPrimaryContainer: Color(0xFF000000),
    primaryFixed: Color(0xFFDCE6FA),
    primaryFixedDim: Color(0xFFDCE6FA),
    onPrimaryFixed: Color(0xFF000000),
    onPrimaryFixedVariant: Color(0xFF000000),
    secondary: Color(0xFF4F3500),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFF0C2),
    onSecondaryContainer: Color(0xFF000000),
    secondaryFixed: Color(0xFFFFF0C2),
    secondaryFixedDim: Color(0xFFFFF0C2),
    onSecondaryFixed: Color(0xFF000000),
    onSecondaryFixedVariant: Color(0xFF000000),
    tertiary: Color(0xFF00463A),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFD6F5EA),
    onTertiaryContainer: Color(0xFF000000),
    tertiaryFixed: Color(0xFFD6F5EA),
    tertiaryFixedDim: Color(0xFFD6F5EA),
    onTertiaryFixed: Color(0xFF000000),
    onTertiaryFixedVariant: Color(0xFF000000),
    error: Color(0xFF8C0000),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFE0DC),
    onErrorContainer: Color(0xFF000000),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF000000),
    surfaceDim: Color(0xFFE0E0E0),
    surfaceBright: Color(0xFFFFFFFF),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFFFFFFF),
    surfaceContainer: Color(0xFFF2F2F2),
    surfaceContainerHigh: Color(0xFFEBEBEB),
    surfaceContainerHighest: Color(0xFFE0E0E0),
    onSurfaceVariant: Color(0xFF1F1F1F),
    outline: Color(0xFF000000),
    outlineVariant: Color(0xFF4D4D4D),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF000000),
    onInverseSurface: Color(0xFFFFFFFF),
    inversePrimary: Color(0xFFB5CEFF),
    surfaceTint: Colors.transparent,
  );

  /// High contrast dark: white on black, every text pair at 7:1 or more.
  static const hcDark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFB5CEFF),
    onPrimary: Color(0xFF000000),
    primaryContainer: Color(0xFF1B2A45),
    onPrimaryContainer: Color(0xFFFFFFFF),
    primaryFixed: Color(0xFF1B2A45),
    primaryFixedDim: Color(0xFF1B2A45),
    onPrimaryFixed: Color(0xFFFFFFFF),
    onPrimaryFixedVariant: Color(0xFFFFFFFF),
    secondary: Color(0xFFFFD970),
    onSecondary: Color(0xFF000000),
    secondaryContainer: Color(0xFF3D2E00),
    onSecondaryContainer: Color(0xFFFFFFFF),
    secondaryFixed: Color(0xFF3D2E00),
    secondaryFixedDim: Color(0xFF3D2E00),
    onSecondaryFixed: Color(0xFFFFFFFF),
    onSecondaryFixedVariant: Color(0xFFFFFFFF),
    tertiary: Color(0xFF7FE3C2),
    onTertiary: Color(0xFF000000),
    tertiaryContainer: Color(0xFF003D2E),
    onTertiaryContainer: Color(0xFFFFFFFF),
    tertiaryFixed: Color(0xFF003D2E),
    tertiaryFixedDim: Color(0xFF003D2E),
    onTertiaryFixed: Color(0xFFFFFFFF),
    onTertiaryFixedVariant: Color(0xFFFFFFFF),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF000000),
    errorContainer: Color(0xFF4A0000),
    onErrorContainer: Color(0xFFFFFFFF),
    surface: Color(0xFF000000),
    onSurface: Color(0xFFFFFFFF),
    surfaceDim: Color(0xFF000000),
    surfaceBright: Color(0xFF262626),
    surfaceContainerLowest: Color(0xFF000000),
    surfaceContainerLow: Color(0xFF000000),
    surfaceContainer: Color(0xFF0F0F0F),
    surfaceContainerHigh: Color(0xFF1A1A1A),
    surfaceContainerHighest: Color(0xFF262626),
    onSurfaceVariant: Color(0xFFEBEBEB),
    outline: Color(0xFFFFFFFF),
    outlineVariant: Color(0xFFB3B3B3),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFFFFFFF),
    onInverseSurface: Color(0xFF000000),
    inversePrimary: Color(0xFF0A2A5E),
    surfaceTint: Colors.transparent,
  );

  /// SeferColors for each theme (§3.3).
  static const seferLight = SeferColors(
    paper: Color(0xFFFFFDF8),
    hairline: Color(0xFFD8CFBF),
    hairlineWidth: 1,
    goldLeaf: Color(0xFFB38D3F),
    ringMikra1: Color(0xFF1D3F75),
    ringMikra2: Color(0xFF55779F),
    ringTargum: Color(0xFF946C1E),
    ringTrack: Color(0xFFE8E1D3),
    restWash: Color(0xFFF2E7CD),
    focus: Color(0xFF1D3F75),
    focusGap: Color(0xFFFAF7F0),
    dimInk: Color(0xFF716859),
    verseHighlight: Color(0xFFFFFDF8),
    isHighContrast: false,
  );

  static const seferDark = SeferColors(
    paper: Color(0xFF1C1915),
    hairline: Color(0xFF4A443A),
    hairlineWidth: 1,
    goldLeaf: Color(0xFFB8954B),
    ringMikra1: Color(0xFFAFC6EE),
    ringMikra2: Color(0xFF7E9BC8),
    ringTargum: Color(0xFFC9A458),
    ringTrack: Color(0xFF36312A),
    restWash: Color(0xFF4A3A16),
    focus: Color(0xFFAFC6EE),
    focusGap: Color(0xFF14120F),
    dimInk: Color(0xFF9C9384),
    verseHighlight: Color(0xFF1C1915),
    isHighContrast: false,
  );

  static const seferSepia = SeferColors(
    paper: Color(0xFFFAF3E3),
    hairline: Color(0xFFCBB994),
    hairlineWidth: 1,
    goldLeaf: Color(0xFFA9853A),
    ringMikra1: Color(0xFF25406C),
    ringMikra2: Color(0xFF4F6B92),
    ringTargum: Color(0xFF8A651C),
    ringTrack: Color(0xFFE0D3B4),
    restWash: Color(0xFFEADBB4),
    focus: Color(0xFF25406C),
    focusGap: Color(0xFFF3E9D2),
    dimInk: Color(0xFF6E5F49),
    verseHighlight: Color(0xFFFAF3E3),
    isHighContrast: false,
  );

  static const seferHcLight = SeferColors(
    paper: Color(0xFFFFFFFF),
    hairline: Color(0xFF000000),
    hairlineWidth: 2,
    goldLeaf: Color(0xFF4F3500),
    ringMikra1: Color(0xFF0A2A5E),
    ringMikra2: Color(0xFF2F4F82),
    ringTargum: Color(0xFF4F3500),
    ringTrack: Color(0xFFE0E0E0),
    restWash: Color(0xFFFFF0C2),
    focus: Color(0xFF000000),
    focusGap: Color(0xFFFFFFFF),
    dimInk: Color(0xFF1F1F1F),
    verseHighlight: Colors.transparent,
    isHighContrast: true,
  );

  static const seferHcDark = SeferColors(
    paper: Color(0xFF000000),
    hairline: Color(0xFFFFFFFF),
    hairlineWidth: 2,
    goldLeaf: Color(0xFFFFD970),
    ringMikra1: Color(0xFFB5CEFF),
    ringMikra2: Color(0xFF8FB0F0),
    ringTargum: Color(0xFFFFD970),
    ringTrack: Color(0xFF333333),
    restWash: Color(0xFF3D2E00),
    focus: Color(0xFFFFFFFF),
    focusGap: Color(0xFF000000),
    dimInk: Color(0xFFEBEBEB),
    verseHighlight: Colors.transparent,
    isHighContrast: true,
  );

  /// StatusColors for each theme (§3.4).
  static const statusLight = StatusColors(
    done: Color(0xFF1D3F75),
    onDone: Color(0xFFFFFFFF),
    late: Color(0xFF4A6A9B),
    onLate: Color(0xFFFFFFFF),
    overdue: Color(0xFF7A5712),
    grace: Color(0xFF2E6A56),
    neutral: Color(0xFF7D7466),
    rest: Color(0xFF7A5712),
  );

  static const statusDark = StatusColors(
    done: Color(0xFFAFC6EE),
    onDone: Color(0xFF0E2547),
    late: Color(0xFF8199C6),
    onLate: Color(0xFF0E2547),
    overdue: Color(0xFFDDB96B),
    grace: Color(0xFF8FD0B6),
    neutral: Color(0xFF958C7D),
    rest: Color(0xFFDDB96B),
  );

  static const statusSepia = StatusColors(
    done: Color(0xFF25406C),
    onDone: Color(0xFFFFFFFF),
    late: Color(0xFF46628C),
    onLate: Color(0xFFFFFFFF),
    overdue: Color(0xFF6C4B0E),
    grace: Color(0xFF2B6350),
    neutral: Color(0xFF7C6C55),
    rest: Color(0xFF6C4B0E),
  );

  static const statusHcLight = StatusColors(
    done: Color(0xFF0A2A5E),
    onDone: Color(0xFFFFFFFF),
    late: Color(0xFF2F4F82),
    onLate: Color(0xFFFFFFFF),
    overdue: Color(0xFF4F3500),
    grace: Color(0xFF00463A),
    neutral: Color(0xFF4D4D4D),
    rest: Color(0xFF4F3500),
  );

  static const statusHcDark = StatusColors(
    done: Color(0xFFB5CEFF),
    onDone: Color(0xFF000000),
    late: Color(0xFF8FB0F0),
    onLate: Color(0xFF000000),
    overdue: Color(0xFFFFD970),
    grace: Color(0xFF7FE3C2),
    neutral: Color(0xFFBDBDBD),
    rest: Color(0xFFFFD970),
  );
}
