import 'dart:convert';
import 'dart:io';

/// Loads a JSON fixture generated by tool/data/gen_fixtures.mjs.
dynamic loadFixture(String name) =>
    jsonDecode(File('test/fixtures/$name').readAsStringSync());
