{{flutter_js}}
{{flutter_build_config}}

// Without serviceWorkerSettings, the loader leaves out Flutter's own service
// worker, which is deprecated and now only unregisters itself. sw.js,
// generated by Workbox from workbox-config.cjs once the app is built, keeps
// the app working offline instead.
_flutter.loader.load();

if ('serviceWorker' in navigator) {
  // Room for every file the first visit loads (see below).
  performance.setResourceTimingBufferSize(500);
  // Registered once the app is up, so the worker's downloads don't slow it.
  window.addEventListener('flutter-first-frame', function () {
    var firstVisit = !navigator.serviceWorker.controller;
    navigator.serviceWorker.register('sw.js')
      .then(function () { return navigator.serviceWorker.ready; })
      .then(function (registration) {
        if (!firstVisit || !registration.active) return;
        // The engine, the fonts and any book opened so far loaded before the
        // worker could cache them; it caches them now (Workbox's CACHE_URLS
        // message), so the app works offline after this first visit.
        var urls = performance.getEntriesByType('resource')
          .map(function (entry) { return entry.name.split('#')[0]; })
          .filter(function (url) {
            return url.indexOf(location.origin + '/') === 0 && /\/(canvaskit|assets)\//.test(url);
          });
        registration.active.postMessage({ type: 'CACHE_URLS', payload: { urlsToCache: urls } });
      })
      .catch(function (error) { console.warn('Offline support is unavailable:', error); });
  }, { once: true });
}
